---
- name: List missing patches (packages) on Oracle Linux
  hosts: all
  become: yes
  tasks:
    - name: Check for available updates
      yum:
        list: updates
      register: yum_updates

    - name: Display missing package names
      debug:
        msg: "{{ item.pkgname }}"
      loop: "{{ yum_updates.results }}"
      when: yum_updates.results is defined and yum_updates.results | length > 0
